# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

City.create([
	{ name: 'Wonosobo' },
	{ name: 'Aceh Barat' },
	{ name: 'Aceh Barat Daya' },
	{ name: 'Aceh Besar' },
	{ name: 'Aceh Jaya' },
	{ name: 'Aceh Selatan' },
	{ name: 'Aceh Singkil' },
	{ name: 'Aceh Tamiang' },
	{ name: 'Aceh Tengah' },
	{ name: 'Aceh Tenggara' },
	{ name: 'Aceh Timur' },
	{ name: 'Aceh Utara' },
	{ name: 'Agam' },
	{ name: 'Alor' },
	{ name: 'Asahan' },
	{ name: 'Asmat' },
	{ name: 'Badung' },
	{ name: 'Balangan' },
	{ name: 'Bandung' },
	{ name: 'Bandung Barat' },
	{ name: 'Banggai' },
	{ name: 'Banggai Kepulauan' },
	{ name: 'Banggai Laut' },
	{ name: 'Bangka' },
	{ name: 'Bangka Barat' },
	{ name: 'Bangka Selatan' },
	{ name: 'Bangka Tengah' },
	{ name: 'Bangkalan' },
	{ name: 'Bangli' },
	{ name: 'Banjar' },
	{ name: 'Banjarnegara' },
	{ name: 'Bantaeng' },
	{ name: 'Bantul' },
	{ name: 'Banyuasin' },
	{ name: 'Banyumas' },
	{ name: 'Banyuwangi' },
	{ name: 'Barito Kuala' },
	{ name: 'Barito Selatan' },
	{ name: 'Barito Timur' },
	{ name: 'Barito Utara' },
	{ name: 'Barru' },
	{ name: 'Batang' },
	{ name: 'Batang Hari' },
	{ name: 'Batu Bara' },
	{ name: 'Bekasi selected=' },
	{ name: 'Belitung' },
	{ name: 'Belitung Timur' },
	{ name: 'Belu' },
	{ name: 'Bener Meriah' },
	{ name: 'Bengkalis' },
	{ name: 'Bengkayang' },
	{ name: 'Bengkulu Selatan' },
	{ name: 'Bengkulu Tengah' },
	{ name: 'Bengkulu Utara' },
	{ name: 'Berau' },
	{ name: 'Biak Numfor' },
	{ name: 'Bima' },
	{ name: 'Bintan' },
	{ name: 'Bireuen' },
	{ name: 'Blitar' },
	{ name: 'Blora' },
	{ name: 'Boalemo' },
	{ name: 'Bogor' },
	{ name: 'Bojonegoro' },
	{ name: 'Bolaang Mongondow' },
	{ name: 'Bolaang Mongondow Selatan' },
	{ name: 'Bolaang Mongondow Timur' },
	{ name: 'Bolaang Mongondow Utara' },
	{ name: 'Bombana' },
	{ name: 'Bondowoso' },
	{ name: 'Bone' },
	{ name: 'Bone Bolango' },
	{ name: 'Boven Digoel' },
	{ name: 'Boyolali' },
	{ name: 'Brebes' },
	{ name: 'Buleleng' },
	{ name: 'Bulukumba' },
	{ name: 'Bulungan' },
	{ name: 'Bungo' },
	{ name: 'Buol' },
	{ name: 'Buru' },
	{ name: 'Buru Selatan' },
	{ name: 'Buton' },
	{ name: 'Buton Selatan' },
	{ name: 'Buton Tengah' },
	{ name: 'Buton Utara' },
	{ name: 'Ciamis' },
	{ name: 'Cianjur' },
	{ name: 'Cilacap' },
	{ name: 'Cirebon' },
	{ name: 'Dairi' },
	{ name: 'Deiyai' },
	{ name: 'Deli Serdang' },
	{ name: 'Demak' },
	{ name: 'Dharmasraya' },
	{ name: 'Dogiyai' },
	{ name: 'Dompu' },
	{ name: 'Donggala' },
	{ name: 'Empat Lawang' },
	{ name: 'Ende' },
	{ name: 'Enrekang' },
	{ name: 'Fakfak' },
	{ name: 'Flores Timur' },
	{ name: 'Garut' },
	{ name: 'Gayo Lues' },
	{ name: 'Gianyar' },
	{ name: 'Gorontalo' },
	{ name: 'Gorontalo Utara' },
	{ name: 'Gowa' },
	{ name: 'Gresik' },
	{ name: 'Grobogan' },
	{ name: 'Gunung Kidul' },
	{ name: 'Gunung Mas' },
	{ name: 'Halmahera Barat' },
	{ name: 'Halmahera Selatan' },
	{ name: 'Halmahera Tengah' },
	{ name: 'Halmahera Timur' },
	{ name: 'Halmahera Utara' },
	{ name: 'Hulu Sungai Selatan' },
	{ name: 'Hulu Sungai Tengah' },
	{ name: 'Hulu Sungai Utara' },
	{ name: 'Humbang Hasundutan' },
	{ name: 'Indragiri Hilir' },
	{ name: 'Indragiri Hulu' },
	{ name: 'Indramayu' },
	{ name: 'Intan Jaya' },
	{ name: 'Jayapura' },
	{ name: 'Jayawijaya' },
	{ name: 'Jember' },
	{ name: 'Jembrana' },
	{ name: 'Jeneponto' },
	{ name: 'Jepara' },
	{ name: 'Jombang' },
	{ name: 'Kaimana' },
	{ name: 'Kampar' },
	{ name: 'Kapuas' },
	{ name: 'Kapuas Hulu' },
	{ name: 'Karanganyar' },
	{ name: 'Karangasem' },
	{ name: 'Karawang' },
	{ name: 'Karimun' },
	{ name: 'Karo' },
	{ name: 'Katingan' },
	{ name: 'Kaur' },
	{ name: 'Kayong Utara' },
	{ name: 'Kebumen' },
	{ name: 'Kediri' },
	{ name: 'Keerom' },
	{ name: 'Kendal' },
	{ name: 'Kepahiang' },
	{ name: 'Kepulauan Anambas' },
	{ name: 'Kepulauan Aru' },
	{ name: 'Kepulauan Mentawai' },
	{ name: 'Kepulauan Meranti' },
	{ name: 'Kepulauan Sangihe' },
	{ name: 'Kepulauan Selayar' },
	{ name: 'Kepulauan Seribu' },
	{ name: 'Kepulauan Siau Tagulandang Biaro' },
	{ name: 'Kepulauan Sula' },
	{ name: 'Kepulauan Talaud' },
	{ name: 'Kepulauan Yapen' },
	{ name: 'Kerinci' },
	{ name: 'Ketapang' },
	{ name: 'Klaten' },
	{ name: 'Klungkung' },
	{ name: 'Kolaka' },
	{ name: 'Kolaka Timur' },
	{ name: 'Kolaka Utara' },
	{ name: 'Konawe' },
	{ name: 'Konawe Kepulauan' },
	{ name: 'Konawe Selatan' },
	{ name: 'Konawe Utara' },
	{ name: 'Kota Ambon' },
	{ name: 'Kota Balikpapan' },
	{ name: 'Kota Banda Aceh' },
	{ name: 'Kota Bandar Lampung' },
	{ name: 'Kota Bandung' },
	{ name: 'Kota Banjar' },
	{ name: 'Kota Banjar baru' },
	{ name: 'Kota Banjarmasin' },
	{ name: 'Kota baru' },
	{ name: 'Kota Batam' },
	{ name: 'Kota Batu' },
	{ name: 'Kota Bau-Bau' },
	{ name: 'Kota Bekasi' },
	{ name: 'Kota Bengkulu' },
	{ name: 'Kota Bima' },
	{ name: 'Kota Binjai' },
	{ name: 'Kota Bitung' },
	{ name: 'Kota Blitar' },
	{ name: 'Kota Bogor' },
	{ name: 'Kota Bontang' },
	{ name: 'Kota Bukittinggi' },
	{ name: 'Kota Cilegon' },
	{ name: 'Kota Cimahi' },
	{ name: 'Kota Cirebon' },
	{ name: 'Kota Denpasar' },
	{ name: 'Kota Depok' },
	{ name: 'Kota Dumai' },
	{ name: 'Kota Gorontalo' },
	{ name: 'Kota Gunungsitoli' },
	{ name: 'Kota Jakarta Barat' },
	{ name: 'Kota Jakarta Pusat' },
	{ name: 'Kota Jakarta Selatan' },
	{ name: 'Kota Jakarta Timur' },
	{ name: 'Kota Jakarta Utara' },
	{ name: 'Kota Jambi' },
	{ name: 'Kota Jayapura' },
	{ name: 'Kota Kediri' },
	{ name: 'Kota Kendari' },
	{ name: 'Kota Kotamobagu' },
	{ name: 'Kota Kupang' },
	{ name: 'Kota Langsa' },
	{ name: 'Kota Lhokseumawe' },
	{ name: 'Kota Lubuk Linggau' },
	{ name: 'Kota Madiun' },
	{ name: 'Kota Magelang' },
	{ name: 'Kota Makassar' },
	{ name: 'Kota Malang' },
	{ name: 'Kota Manado' },
	{ name: 'Kota Mataram' },
	{ name: 'Kota Medan' },
	{ name: 'Kota Metro' },
	{ name: 'Kota Mojokerto' },
	{ name: 'Kota Padang' },
	{ name: 'Kota Padang Panjang' },
	{ name: 'Kota Padang Sidempuan' },
	{ name: 'Kota Pagar Alam' },
	{ name: 'Kota Palangka Raya' },
	{ name: 'Kota Palembang' },
	{ name: 'Kota Palopo' },
	{ name: 'Kota Palu' },
	{ name: 'Kota Pangkal Pinang' },
	{ name: 'Kota Pare-pare' },
	{ name: 'Kota Pariaman' },
	{ name: 'Kota Pasuruan' },
	{ name: 'Kota Payakumbuh' },
	{ name: 'Kota Pekalongan' },
	{ name: 'Kota Pekanbaru' },
	{ name: 'Kota Pematang Siantar' },
	{ name: 'Kota Pontianak' },
	{ name: 'Kota Prabumulih' },
	{ name: 'Kota Probolinggo' },
	{ name: 'Kota Sabang' },
	{ name: 'Kota Salatiga' },
	{ name: 'Kota Samarinda' },
	{ name: 'Kota Sawah Lunto' },
	{ name: 'Kota Semarang' },
	{ name: 'Kota Serang' },
	{ name: 'Kota Sibolga' },
	{ name: 'Kota Singkawang' },
	{ name: 'Kota Solok' },
	{ name: 'Kota Sorong' },
	{ name: 'Kota Subulussalam' },
	{ name: 'Kota Sukabumi' },
	{ name: 'Kota Sungai penuh' },
	{ name: 'Kota Surabaya' },
	{ name: 'Kota Surakarta' },
	{ name: 'Kota Tangerang' },
	{ name: 'Kota Tangerang Selatan' },
	{ name: 'Kota Tanjung Balai' },
	{ name: 'Kota Tanjung Pinang' },
	{ name: 'Kota Tarakan' },
	{ name: 'Kota Tasikmalaya' },
	{ name: 'Kota Tebing Tinggi' },
	{ name: 'Kota Tegal' },
	{ name: 'Kota Ternate' },
	{ name: 'Kota Tidore Kepulauan' },
	{ name: 'Kota Tomohon' },
	{ name: 'Kota Tual' },
	{ name: 'Kota Yogyakarta' },
	{ name: 'Kotawaringin Barat' },
	{ name: 'Kotawaringin Timur' },
	{ name: 'Kuantan Singingi' },
	{ name: 'Kubu Raya' },
	{ name: 'Kudus' },
	{ name: 'Kulon Progo' },
	{ name: 'Kuningan' },
	{ name: 'Kupang' },
	{ name: 'Kutai Barat' },
	{ name: 'Kutai Kartanegara' },
	{ name: 'Kutai Timur' },
	{ name: 'Labuhan Batu' },
	{ name: 'Labuhan Batu Selatan' },
	{ name: 'Labuhan Batu Utara' },
	{ name: 'Lahat' },
	{ name: 'Lamandau' },
	{ name: 'Lamongan' },
	{ name: 'Lampung Barat' },
	{ name: 'Lampung Selatan' },
	{ name: 'Lampung Tengah' },
	{ name: 'Lampung Timur' },
	{ name: 'Lampung Utara' },
	{ name: 'Landak' },
	{ name: 'Langkat' },
	{ name: 'Lanny Jaya' },
	{ name: 'Lebak' },
	{ name: 'Lebong' },
	{ name: 'Lembata' },
	{ name: 'Lima Puluh Kota' },
	{ name: 'Lingga' },
	{ name: 'Lombok Barat' },
	{ name: 'Lombok Tengah' },
	{ name: 'Lombok Timur' },
	{ name: 'Lombok Utara' },
	{ name: 'Lumajang' },
	{ name: 'Luwu' },
	{ name: 'Luwu Timur' },
	{ name: 'Luwu Utara' },
	{ name: 'Madiun' },
	{ name: 'Magelang' },
	{ name: 'Magetan' },
	{ name: 'Mahakam Hulu' },
	{ name: 'Majalengka' },
	{ name: 'Majene' },
	{ name: 'Malaka' },
	{ name: 'Malang' },
	{ name: 'Malinau' },
	{ name: 'Maluku Barat Daya' },
	{ name: 'Maluku Tengah' },
	{ name: 'Maluku Tenggara' },
	{ name: 'Maluku Tenggara Barat' },
	{ name: 'Mamasa' },
	{ name: 'Mamberamo Raya' },
	{ name: 'Mamberamo Tengah' },
	{ name: 'Mamuju' },
	{ name: 'Mamuju Tengah' },
	{ name: 'Mandailing Natal' },
	{ name: 'Manggarai' },
	{ name: 'Manggarai Barat' },
	{ name: 'Manggarai Timur' },
	{ name: 'Manokwari' },
	{ name: 'Manokwari Selatan' },
	{ name: 'Mappi' },
	{ name: 'Maros' },
	{ name: 'Maybrat' },
	{ name: 'Melawi' },
	{ name: 'Mempawah' },
	{ name: 'Merangin' },
	{ name: 'Merauke' },
	{ name: 'Mesuji' },
	{ name: 'Mimika' },
	{ name: 'Minahasa' },
	{ name: 'Minahasa Selatan' },
	{ name: 'Minahasa Tenggara' },
	{ name: 'Minahasa Utara' },
	{ name: 'Mojokerto' },
	{ name: 'Morowali' },
	{ name: 'Morowali Utara' },
	{ name: 'Muara Enim' },
	{ name: 'Muaro Jambi' },
	{ name: 'Muko Muko' },
	{ name: 'Muna' },
	{ name: 'Muna Barat' },
	{ name: 'Murung Raya' },
	{ name: 'Musi Banyuasin' },
	{ name: 'Musi Rawas' },
	{ name: 'Musi Rawas Utara' },
	{ name: 'Nabire' },
	{ name: 'Nagan Raya' },
	{ name: 'Nagekeo' },
	{ name: 'Natuna' },
	{ name: 'Nduga' },
	{ name: 'Ngada' },
	{ name: 'Nganjuk' },
	{ name: 'Ngawi' },
	{ name: 'Nias' },
	{ name: 'Nias Barat' },
	{ name: 'Nias Selatan' },
	{ name: 'Nias Utara' },
	{ name: 'Nunukan' },
	{ name: 'Ogan Ilir' },
	{ name: 'Ogan Komering Ilir' },
	{ name: 'Ogan Komering Ulu' },
	{ name: 'Ogan Komering Ulu Selatan' },
	{ name: 'Ogan Komering Ulu Timur' },
	{ name: 'Pacitan' },
	{ name: 'Padang Lawas' },
	{ name: 'Padang Lawas Utara' },
	{ name: 'Padang Pariaman' },
	{ name: 'Pakpak Bharat' },
	{ name: 'Pamekasan' },
	{ name: 'Pandeglang' },
	{ name: 'Pangandaran' },
	{ name: 'Pangkajene Kepulauan' },
	{ name: 'Paniai' },
	{ name: 'Parigi Moutong' },
	{ name: 'Pasaman' },
	{ name: 'Pasaman Barat' },
	{ name: 'Pasangkayu' },
	{ name: 'Paser' },
	{ name: 'Pasuruan' },
	{ name: 'Pati' },
	{ name: 'Pegunungan Arfak' },
	{ name: 'Pegunungan Bintang' },
	{ name: 'Pekalongan' },
	{ name: 'Pelalawan' },
	{ name: 'Pemalang' },
	{ name: 'Penajam Paser Utara' },
	{ name: 'Penukal Abab Lematang Ilir ' },
	{ name: 'Pesawaran' },
	{ name: 'Pesisir Barat' },
	{ name: 'Pesisir Selatan' },
	{ name: 'Pidie' },
	{ name: 'Pidie Jaya' },
	{ name: 'Pinrang' },
	{ name: 'Pohuwato' },
	{ name: 'Polewali Mandar' },
	{ name: 'Ponorogo' },
	{ name: 'Poso' },
	{ name: 'Pringsewu' },
	{ name: 'Probolinggo' },
	{ name: 'Pulang Pisau' },
	{ name: 'Pulau Morotai' },
	{ name: 'Pulau Taliabu' },
	{ name: 'Puncak' },
	{ name: 'Puncak Jaya' },
	{ name: 'Purbalingga' },
	{ name: 'Purwakarta' },
	{ name: 'Purworejo' },
	{ name: 'Raja Ampat' },
	{ name: 'Rejang Lebong' },
	{ name: 'Rembang' },
	{ name: 'Rokan Hilir' },
	{ name: 'Rokan Hulu' },
	{ name: 'Rote Ndao' },
	{ name: 'Sabu Raijua' },
	{ name: 'Sambas' },
	{ name: 'Samosir' },
	{ name: 'Sampang' },
	{ name: 'Sanggau' },
	{ name: 'Sarmi' },
	{ name: 'Sarolangun' },
	{ name: 'Sekadau' },
	{ name: 'Seluma' },
	{ name: 'Semarang' },
	{ name: 'Seram Bagian Barat' },
	{ name: 'Seram Bagian Timur' },
	{ name: 'Serang' },
	{ name: 'Serdang Bedagai' },
	{ name: 'Seruyan' },
	{ name: 'Siak' },
	{ name: 'Sidenreng Rappang' },
	{ name: 'Sidoarjo' },
	{ name: 'Sigi' },
	{ name: 'Sijunjung' },
	{ name: 'Sikka' },
	{ name: 'Simalungun' },
	{ name: 'Simeulue' },
	{ name: 'Sinjai' },
	{ name: 'Sintang' },
	{ name: 'Situbondo' },
	{ name: 'Sleman' },
	{ name: 'Solok' },
	{ name: 'Solok Selatan' },
	{ name: 'Soppeng' },
	{ name: 'Sorong' },
	{ name: 'Sorong Selatan' },
	{ name: 'Sragen' },
	{ name: 'Subang' },
	{ name: 'Sukabumi' },
	{ name: 'Sukamara' },
	{ name: 'Sukoharjo' },
	{ name: 'Sumba Barat' },
	{ name: 'Sumba Barat Daya' },
	{ name: 'Sumba Tengah' },
	{ name: 'Sumba Timur' },
	{ name: 'Sumbawa' },
	{ name: 'Sumbawa Barat' },
	{ name: 'Sumedang' },
	{ name: 'Sumenep' },
	{ name: 'Supiori' },
	{ name: 'Tabalong' },
	{ name: 'Tabanan' },
	{ name: 'Takalar' },
	{ name: 'Tambrauw' },
	{ name: 'Tana Tidung' },
	{ name: 'Tana Toraja' },
	{ name: 'Tanah Bumbu' },
	{ name: 'Tanah Datar' },
	{ name: 'Tanah Laut' },
	{ name: 'Tangerang' },
	{ name: 'Tanggamus' },
	{ name: 'Tanjung Jabung Barat' },
	{ name: 'Tanjung Jabung Timur' },
	{ name: 'Tapanuli Selatan' },
	{ name: 'Tapanuli Tengah' },
	{ name: 'Tapanuli Utara' },
	{ name: 'Tapin' },
	{ name: 'Tasikmalaya' },
	{ name: 'Tebo' },
	{ name: 'Tegal' },
	{ name: 'Teluk Bintuni' },
	{ name: 'Teluk Wondama' },
	{ name: 'Temanggung' },
	{ name: 'Timor Tengah Selatan' },
	{ name: 'Timor Tengah Utara' },
	{ name: 'Toba Samosir' },
	{ name: 'Tojo Una-Una' },
	{ name: 'Toli-Toli' },
	{ name: 'Tolikara' },
	{ name: 'Toraja Utara' },
	{ name: 'Trenggalek' },
	{ name: 'Tuban' },
	{ name: 'Tulang Bawang' },
	{ name: 'Tulang Bawang Barat' },
	{ name: 'Tulungagung' },
	{ name: 'Wajo' },
	{ name: 'Wakatobi' },
	{ name: 'Waropen' },
	{ name: 'Way Kanan' },
	{ name: 'Wonogiri' },
	{ name: 'Yahukimo' },
	{ name: 'Yalimo' }
])
bekasi = City.create(name: 'Bekasi')

hospital_1 = Hospital.create(name: 'Hermina Galaxy', city: bekasi)
Doctor.create([
                { name: 'AGNES YUNIE P, DR', speciality: 'ANAK', hospital: hospital_1 },
                { name: 'ALI SYAUGI BADRIQ, DR', speciality: 'ANAK', hospital: hospital_1 },
                { name: 'AYI DILLA SEPTARINI, DR', speciality: 'ANAK', hospital: hospital_1 },
                { name: 'BARALANGI TAMBING, DR', speciality: 'ANAK', hospital: hospital_1 },
                { name: 'DEDI RAHMAT, DR', speciality: 'ANAK', hospital: hospital_1 },
                { name: 'EDI PASARIBU, DR', speciality: 'ANAK', hospital: hospital_1 },
                { name: 'FISIOTHERAPI', speciality: 'ANAK', hospital: hospital_1 },
                { name: 'IDA SUSILAWATI, DR', speciality: 'ANAK', hospital: hospital_1},
                { name: 'JULIA K KADANG, DR', speciality: 'ANAK', hospital: hospital_1},
                { name: 'KHAIRANI DIMAN, DR', speciality: 'ANAK', hospital: hospital_1},
                { name: 'LAILY FATCHIYAH, DR', speciality: 'ANAK', hospital: hospital_1},
                { name: 'LANNY C GULTOM, DR', speciality: 'ANAK', hospital: hospital_1},
                { name: 'MAS WISHNUWARDHANA, DR', speciality: 'ANAK', hospital: hospital_1},
                { name: 'MIRA, DR', speciality: 'ANAK', hospital: hospital_1},
                { name: 'NGAKAN PUTU SUTARMAN, DR', speciality: 'ANAK', hospital: hospital_1},
                { name: 'NOVARINA, DR', speciality: 'ANAK', hospital: hospital_1},
                { name: 'NUNUNG SITI HINDUN, DR', speciality: 'ANAK', hospital: hospital_1},
                { name: 'PATRICIA AGNETHA P, DR', speciality: 'ANAK', hospital: hospital_1},
                { name: 'RATNA NAPITUPULU, DR', speciality: 'ANAK', hospital: hospital_1},
                { name: 'RINNA W, DR', speciality: 'ANAK', hospital: hospital_1},
                { name: 'RITA ANDRIYANI, DR', speciality: 'ANAK', hospital: hospital_1},
                { name: 'SANG AYU PUTU SRI MAS A, DR', speciality: 'ANAK', hospital: hospital_1},
                { name: 'TRIZA ARIF, DR', speciality: 'ANAK', hospital: hospital_1},
                { name: 'TUMPAL YANSEN S, DR', speciality: 'ANAK', hospital: hospital_1},
                { name: 'WYNDA FELISIA, DR', speciality: 'ANAK', hospital: hospital_1}
              ])

hospital_2 = Hospital.create(name: 'Mitra Keluarga Bekasi', city: bekasi)
Doctor.create([
                { name: 'drg. Arlan Akbari', speciality: 'GIGI', hospital: hospital_2},
                { name: 'drg. Dina Riyanti, Sp.Ort', speciality: 'GIGI', hospital: hospital_2},
                { name: 'drg. Helmiyanis, Sp. KG', speciality: 'GIGI', hospital: hospital_2},
                { name: 'drg. Robert Lessang, Sp. Perio', speciality: 'GIGI', hospital: hospital_2},
                { name: 'drg. Sulistyowati', speciality: 'GIGI', hospital: hospital_2},
                { name: 'drg. Syafril Gafar', speciality: 'GIGI', hospital: hospital_2},
                { name: 'drg. Tita Agustia', speciality: 'GIGI', hospital: hospital_2},
                { name: 'drg.Yura Muharsya Sp.KG', speciality: 'GIGI', hospital: hospital_2},
              ])

Hospital.create([
	{ name: 'RS Umum Daerah Kab.Bekasi', city: bekasi},
	{ name: 'RS Umum Hermina Grand Wisata', city: bekasi },
	{ name: 'RS Umum Bhakti Husada', city: bekasi },
	{ name: 'RS Umum Karya Medika', city: bekasi },
	{ name: 'RS Umum Annisa', city: bekasi },
	{ name: 'RS Umum Siloam', city: bekasi },
	{ name: 'RS Umum Sentra Medika', city: bekasi },
	{ name: 'RS Umum Medirossa Cikarang', city: bekasi },
	{ name: 'RS Umum Mitra Keluarga Cikarang', city: bekasi },
	{ name: 'RS Umum Omni Cikarang', city: bekasi },
	{ name: 'RS Umum Hosana Medica', city: bekasi },
	{ name: 'RS Umum Karya Medika II', city: bekasi },
	{ name: 'RS Umum Harapan Keluarga Jababeka', city: bekasi },
	{ name: 'RS Umum Amanda', city: bekasi },
	{ name: 'RS Umum Dokter Adam Talib', city: bekasi },
	{ name: 'RS Umum Asri Medika', city: bekasi },
	{ name: 'RS Umum Cibitung Medika', city: bekasi },
	{ name: 'RS Umum Amanda', city: bekasi },
	{ name: 'RS Umum Ridhoka Salma', city: bekasi },
	{ name: 'RS Umum Permata Keluarga Lippo Cikarang', city: bekasi },
	{ name: 'RS Umum Tiara', city: bekasi },
	{ name: 'RS Umum Medirossa 2', city: bekasi },
	{ name: 'RS Umum Puspa Husada', city: bekasi },
	{ name: 'RS Ibu dan Anak Sayang Bunda', city: bekasi },
	{ name: 'RS Umum Budi Asih', city: bekasi },
	{ name: 'RS Umum Tarumajaya', city: bekasi },
	{ name: 'RS Umum Permata Keluarga Jababeka', city: bekasi },
	{ name: 'RS Cenka', city: bekasi },
	{ name: 'RS Mitra Keluarga Pratama', city: bekasi },
	{ name: 'Rumah Sakit Cenka', city: bekasi }
])
